from turtle import *

tu = Turtle()
tu.speed(0)

#land
tu.up()
tu.setpos(0,-130)
tu.down()
tu.color("darkgreen","darkgreen")
tu.begin_fill()
tu.forward(330)
tu.right(90)
tu.forward(270)
tu.right(90)
tu.forward(660)
tu.right(90)
tu.forward(270)
tu.right(90)
tu.forward(330)
tu.end_fill()

#sky
tu.color("sky blue","sky blue")
tu.begin_fill()
tu.forward(330)
tu.left(90)
tu.forward(400)
tu.left(90)
tu.forward(660)
tu.left(90)
tu.forward(400)
tu.left(90)
tu.forward(330)
tu.end_fill()
tu.right(90)

#rainbow
tu.setpos(0,0)
tu.pensize(13)
col7=['red','orange', 'yellow', 'lawn green', 'steelblue1', 'blue', 'blueviolet']
for i in range(7):
    tu.color(col7[i])
    tu.circle(10*(i+8),-180)
    tu.up()
    tu.setpos(-10*(i+1),0)
    tu.down()
    tu.right(180)

#clouds
tu.pensize(5)
tu.color("white","white")
tu.begin_fill()
#right cloud
tu.setpos(-85,0)
tu.circle(20)
tu.end_fill()
tu.begin_fill()
tu.setpos(-67,0)
tu.circle(30)
tu.end_fill()
tu.begin_fill()
tu.setpos(-20,0)
tu.circle(20)
tu.end_fill()
#left cloud
tu.up()
tu.begin_fill()
tu.setpos(130,0)
tu.down()
tu.circle(20)
tu.end_fill()
tu.begin_fill()
tu.setpos(150,0)
tu.circle(30)
tu.end_fill()
tu.begin_fill()
tu.setpos(195,0)
tu.circle(20)
tu.end_fill()


#The first tree
tu.up()
tu.setpos(-187,0)
tu.down()
tu.right(90)
#Tree trunk
tu.color("brown","brown")
tu.begin_fill()
tu.forward(30)
tu.left(90)
tu.forward(250)
tu.left(90)
tu.forward(30)
tu.left(90)
tu.forward(250)
tu.end_fill()

#tree leaves
#the first part
tu.color("lime green","lime green")
tu.up()
tu.setpos(-100,-100)
tu.down()
tu.begin_fill()
tu.left(90)
tu.forward(200)
tu.right(120)
tu.forward(205)
tu.right(120)
tu.forward(205)
tu.end_fill()
#the second part
tu.up()
tu.setpos(-120,30)
tu.down()
tu.begin_fill()
tu.right(120)
tu.forward(150)
tu.right(120)
tu.forward(150)
tu.right(120)
tu.forward(150)
tu.end_fill()


#birds from afar
#The first bird
tu.up()
tu.setpos(200,200)
tu.down()
tu.color("black","black")
tu.pensize(1)
tu.right(210)
tu.circle(10,180)
tu.right(180)
tu.circle(10,180)
#The second bird
tu.up()
tu.setpos(170,180)
tu.down()
tu.right(180)
tu.circle(10,180)
tu.right(180)
tu.circle(10,180)


#The second tree
tu.up()
tu.pensize(5)
tu.setpos(300,-50)
tu.down()
tu.right(90)
#Tree trunk
tu.color("brown","brown")
tu.begin_fill()
tu.forward(10)
tu.left(90)
tu.forward(100)
tu.left(90)
tu.forward(10)
tu.left(90)
tu.forward(100)
tu.end_fill()
#tree leaves
tu.color("chartreuse3","chartreuse3")
tu.up()
tu.setpos(320,-35)
tu.down()
tu.begin_fill()
tu.circle(20)
tu.end_fill()
tu.color("lawn green","lawn green")
tu.up()
tu.setpos(325,-70)
tu.down()
tu.begin_fill()
tu.circle(20)
tu.end_fill()
tu.color("chartreuse3","chartreuse3")
tu.up()
tu.setpos(300,-70)
tu.down()
tu.begin_fill()
tu.circle(20)
tu.end_fill()
tu.color("green yellow","green yellow")
tu.up()
tu.setpos(310,-10)
tu.down()
tu.begin_fill()
tu.circle(20)
tu.end_fill()
tu.color("green yellow","green yellow")
tu.up()
tu.setpos(280,-50)
tu.down()
tu.begin_fill()
tu.circle(20)
tu.end_fill()
tu.color("lawn green","lawn green")
tu.up()
tu.setpos(300,-40)
tu.down()
tu.begin_fill()
tu.circle(20)
tu.end_fill()

#Lake
tu.up()
tu.setpos(250,-400)
tu.down()
tu.color("Dodgerblue2","Dodgerblue2")
tu.begin_fill()
tu.circle(200,180)
tu.end_fill()

done()